####################################################################################
## 서버 설정 정보
####################################################################################
server:
  port: 7890
  # 세션 타임아웃을 60분으로 설정 (60m)
  servlet:
    context-path: /
    session:
      timeout: 60m
  shutdown: graceful

# logging
logging:
  config: classpath:logback-spring.xml  # logback 설정 파일


####################################################################################
## springboot 공통 설정
####################################################################################
spring:
  application:
    name: point-api
  lifecycle:
    timeout-per-shutdown-phase: 30s

  log:
    file-path: ./log/point-api.log

  datasource:
    url: jdbc:h2:mem:mydata;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always # SQL 스크립트를 항상 실행 (never / embedded / always)
      schema-locations: classpath:schema.sql # 기본값이지만 명시적 지정 가능
      data-locations: classpath:data.sql     # 기본값이지만 명시적 지정 가능


springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true